# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nnhal_raw_tensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nnhal_raw_tensor.proto',
  package='objectDetection',
  syntax='proto3',
  serialized_options=b'\n\"com.intel.examples.objectDetectionB\024objectDetectionProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16nnhal_raw_tensor.proto\x12\x0fobjectDetection\"!\n\x11RequestDataChunks\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1e\n\rRequestString\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0bReplyStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\"C\n\nDataTensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x14\n\x0ctensor_shape\x18\x03 \x03(\x05\"E\n\x10ReplyDataTensors\x12\x31\n\x0c\x64\x61ta_tensors\x18\x01 \x03(\x0b\x32\x1b.objectDetection.DataTensor\"G\n\x12RequestDataTensors\x12\x31\n\x0c\x64\x61ta_tensors\x18\x01 \x03(\x0b\x32\x1b.objectDetection.DataTensor2\xd4\x02\n\tDetection\x12Z\n\x0egetInferResult\x12#.objectDetection.RequestDataTensors\x1a!.objectDetection.ReplyDataTensors\"\x00\x12O\n\x07sendXml\x12\".objectDetection.RequestDataChunks\x1a\x1c.objectDetection.ReplyStatus\"\x00(\x01\x12O\n\x07sendBin\x12\".objectDetection.RequestDataChunks\x1a\x1c.objectDetection.ReplyStatus\"\x00(\x01\x12I\n\x07prepare\x12\x1e.objectDetection.RequestString\x1a\x1c.objectDetection.ReplyStatus\"\x00\x42\x42\n\"com.intel.examples.objectDetectionB\x14objectDetectionProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_REQUESTDATACHUNKS = _descriptor.Descriptor(
  name='RequestDataChunks',
  full_name='objectDetection.RequestDataChunks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='objectDetection.RequestDataChunks.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=76,
)


_REQUESTSTRING = _descriptor.Descriptor(
  name='RequestString',
  full_name='objectDetection.RequestString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='objectDetection.RequestString.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=108,
)


_REPLYSTATUS = _descriptor.Descriptor(
  name='ReplyStatus',
  full_name='objectDetection.ReplyStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='objectDetection.ReplyStatus.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=139,
)


_DATATENSOR = _descriptor.Descriptor(
  name='DataTensor',
  full_name='objectDetection.DataTensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='objectDetection.DataTensor.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_name', full_name='objectDetection.DataTensor.node_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tensor_shape', full_name='objectDetection.DataTensor.tensor_shape', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=208,
)


_REPLYDATATENSORS = _descriptor.Descriptor(
  name='ReplyDataTensors',
  full_name='objectDetection.ReplyDataTensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_tensors', full_name='objectDetection.ReplyDataTensors.data_tensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=279,
)


_REQUESTDATATENSORS = _descriptor.Descriptor(
  name='RequestDataTensors',
  full_name='objectDetection.RequestDataTensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_tensors', full_name='objectDetection.RequestDataTensors.data_tensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=352,
)

_REPLYDATATENSORS.fields_by_name['data_tensors'].message_type = _DATATENSOR
_REQUESTDATATENSORS.fields_by_name['data_tensors'].message_type = _DATATENSOR
DESCRIPTOR.message_types_by_name['RequestDataChunks'] = _REQUESTDATACHUNKS
DESCRIPTOR.message_types_by_name['RequestString'] = _REQUESTSTRING
DESCRIPTOR.message_types_by_name['ReplyStatus'] = _REPLYSTATUS
DESCRIPTOR.message_types_by_name['DataTensor'] = _DATATENSOR
DESCRIPTOR.message_types_by_name['ReplyDataTensors'] = _REPLYDATATENSORS
DESCRIPTOR.message_types_by_name['RequestDataTensors'] = _REQUESTDATATENSORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestDataChunks = _reflection.GeneratedProtocolMessageType('RequestDataChunks', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDATACHUNKS,
  '__module__' : 'nnhal_raw_tensor_pb2'
  # @@protoc_insertion_point(class_scope:objectDetection.RequestDataChunks)
  })
_sym_db.RegisterMessage(RequestDataChunks)

RequestString = _reflection.GeneratedProtocolMessageType('RequestString', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTRING,
  '__module__' : 'nnhal_raw_tensor_pb2'
  # @@protoc_insertion_point(class_scope:objectDetection.RequestString)
  })
_sym_db.RegisterMessage(RequestString)

ReplyStatus = _reflection.GeneratedProtocolMessageType('ReplyStatus', (_message.Message,), {
  'DESCRIPTOR' : _REPLYSTATUS,
  '__module__' : 'nnhal_raw_tensor_pb2'
  # @@protoc_insertion_point(class_scope:objectDetection.ReplyStatus)
  })
_sym_db.RegisterMessage(ReplyStatus)

DataTensor = _reflection.GeneratedProtocolMessageType('DataTensor', (_message.Message,), {
  'DESCRIPTOR' : _DATATENSOR,
  '__module__' : 'nnhal_raw_tensor_pb2'
  # @@protoc_insertion_point(class_scope:objectDetection.DataTensor)
  })
_sym_db.RegisterMessage(DataTensor)

ReplyDataTensors = _reflection.GeneratedProtocolMessageType('ReplyDataTensors', (_message.Message,), {
  'DESCRIPTOR' : _REPLYDATATENSORS,
  '__module__' : 'nnhal_raw_tensor_pb2'
  # @@protoc_insertion_point(class_scope:objectDetection.ReplyDataTensors)
  })
_sym_db.RegisterMessage(ReplyDataTensors)

RequestDataTensors = _reflection.GeneratedProtocolMessageType('RequestDataTensors', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDATATENSORS,
  '__module__' : 'nnhal_raw_tensor_pb2'
  # @@protoc_insertion_point(class_scope:objectDetection.RequestDataTensors)
  })
_sym_db.RegisterMessage(RequestDataTensors)


DESCRIPTOR._options = None

_DETECTION = _descriptor.ServiceDescriptor(
  name='Detection',
  full_name='objectDetection.Detection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=355,
  serialized_end=695,
  methods=[
  _descriptor.MethodDescriptor(
    name='getInferResult',
    full_name='objectDetection.Detection.getInferResult',
    index=0,
    containing_service=None,
    input_type=_REQUESTDATATENSORS,
    output_type=_REPLYDATATENSORS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendXml',
    full_name='objectDetection.Detection.sendXml',
    index=1,
    containing_service=None,
    input_type=_REQUESTDATACHUNKS,
    output_type=_REPLYSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendBin',
    full_name='objectDetection.Detection.sendBin',
    index=2,
    containing_service=None,
    input_type=_REQUESTDATACHUNKS,
    output_type=_REPLYSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='prepare',
    full_name='objectDetection.Detection.prepare',
    index=3,
    containing_service=None,
    input_type=_REQUESTSTRING,
    output_type=_REPLYSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTION)

DESCRIPTOR.services_by_name['Detection'] = _DETECTION

# @@protoc_insertion_point(module_scope)
